#ifndef EEPROM_POSITIONS_H
#define EEPROM_POSITIONS_H


#define ALARM_OFF_AFTER_ADDRESS 0
#define BACK_LIGHT_DURATION_ADDRESS 2
#define TEMPERATURE_REFRESH_PERIOD_ADDRESS 3
#define AUDIO_DELAY_ADDRESS 4
#define ALARMS_TIME_BEGINING_ADDRESS 6



#endif